// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 * Generated by: hibernate/HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
 */
package com.algoTrader.entity.security;

/**
 * @see EquityIndex
 */
public class EquityIndexImpl
    extends EquityIndex
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4087343403938105040L;

}