// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.algoTrader.entity.security;

/**
 * @see com.algoTrader.entity.security.Stock
 */
public class StockDaoImpl
    extends StockDaoBase
{
}