// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 * Generated by: hibernate/HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
 */
package com.algoTrader.entity.security;

/**
 * @see Stock
 */
public class StockImpl
    extends Stock
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6169238869632079681L;

}